### PR TITLE
React & Redux Bookstore CMS: Milestone 5

### PR DESCRIPTION
**Pull request by mke2111**
## Milestone 5:

In this milestone, we added the styles to the app to look almost exactly as the zeplin template give.

- Added the two font families and font sizesused.
- Same colors and background colors

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi team :wave: 

Your styling is almost through, just a change to implement.

* [x] You have a horizontal scroll in the UI you have styled. I will leave gif, kindly use it as a reference.
horizontalScroll

#### Implement this change, then submit another form for a code review.

### ``` Have a great day ``` :slightly_smiling_face: 

#### Uchechukwu Inyama Henry ```

**Comment by mke2111** [comment]
## New Changes:

The horizontal scroll was initially caused by the design specs given specifically the width of 1600px, since a few screens meet this size by default. 
We removed the default screen size given to solve the horizontal scroll.

**Review by wathigo — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED :o:  
Great job on this milestone.
Let's make sure the current changes have been reflected on the hosted version of the app.
Currently, the latest changes have not been implemented on the hosted version.

**After making the changes, make another request for review.**

**Happy Coding :technologist: 
Simon Wathigo**

**Comment by atoledo-ec** [comment]
Hello there, 
Please make sure to refresh the page once you open the live demo link from heroku.

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :traffic_light:

Hi **TEAM**, congratulations on this project :muscle: Awesome job :+1: The local version as well as the online version have no horizontal scroll now :100: 

I hereby approve the project :+1: Kindly go ahead and merge into the development branch
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Pull request merged**
